name: Sync to Personal Repo

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Remove old directory if exists
        run: |
          pwd
          ls
          ls ..
          if [ -d prev ]; then
            rm -rf prev
            echo 'Remove prev directory'
          fi
      - name: Clone repository
        run: |
          cd ..
          git clone --depth 1 --branch main https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/alswo1212/marry-invite.git prev
          ls
          echo 'Clone completed'
      - name: Copy files
        run: |
          pwd
          ls
          ls ..
          rm -rf prev/front
          cp -r front ../prev/front
          echo 'Copy complete'
      - name: Commit and push
        run: |
          cd prev
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m 'commit'
          git push origin main
          echo 'pushed'
